<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INLEN8520064620" failures="1" tests="3" name="Test_reportmanager" time="14.882" errors="0" timestamp="2024-09-17T12:39:40 IST">
  <testcase classname="day46.OrangeHRM" name="testLogo" time="0.097"/>
  <testcase classname="day46.OrangeHRM" name="testAppURL" time="0.043">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day46.OrangeHRM.testAppURL(OrangeHRM.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAppURL -->
  <testcase classname="day46.OrangeHRM" name="testHomePageTittle" time="0.0">
    <skipped/>
  </testcase> <!-- testHomePageTittle -->
</testsuite> <!-- Test_reportmanager -->
